
import { Building, Upgrade, Achievement } from './types';

export const INITIAL_BUILDINGS: Building[] = [
  // --- TIER 0 (BASIC) ---
  {
    id: 'baby_minion',
    name: 'Minion Bebé',
    description: 'Un pequeño ayudante que está aprendiendo. ¡Muy tierno!',
    baseCost: 15,
    baseCps: 0.1,
    owned: 0,
    iconStr: '👶',
    minPrestige: 0,
  },
  {
    id: 'banana_farm',
    name: 'Granja de Bananas',
    description: 'Cultivo hidropónico de bananas de alta calidad.',
    baseCost: 100,
    baseCps: 1,
    owned: 0,
    iconStr: '🍌',
    minPrestige: 0,
  },
  {
    id: 'gru_intern',
    name: 'Becario de Gru',
    description: 'Trabaja gratis... bueno, por bananas.',
    baseCost: 1100,
    baseCps: 8,
    owned: 0,
    iconStr: '🧑‍🔬',
    minPrestige: 0,
  },
  {
    id: 'gru_lab',
    name: 'Laboratorio de Gru',
    description: 'Donde ocurren las ideas malas (y buenas).',
    baseCost: 6000,
    baseCps: 25,
    owned: 0,
    iconStr: '⚗️',
    minPrestige: 0,
  },
  {
    id: 'jelly_factory',
    name: 'Fábrica de Jalea',
    description: 'Producción masiva de la comida favorita de los minions.',
    baseCost: 25000,
    baseCps: 80,
    owned: 0,
    iconStr: '🏭',
    minPrestige: 0,
  },
  {
    id: 'shrink_ray',
    name: 'Rayo Encogedor',
    description: 'Encoge las bananas para que quepan más en el estómago.',
    baseCost: 130000,
    baseCps: 260,
    owned: 0,
    iconStr: '🔫',
    minPrestige: 0,
  },
  {
    id: 'underwater_base',
    name: 'Base Submarina',
    description: 'Oculta bajo el océano para evitar impuestos.',
    baseCost: 550000,
    baseCps: 800,
    owned: 0,
    iconStr: '🐙',
    minPrestige: 0,
  },
  {
    id: 'rocket_ship',
    name: 'Cohete Espacial',
    description: 'Para ir a buscar bananas a otros planetas.',
    baseCost: 1400000,
    baseCps: 1800,
    owned: 0,
    iconStr: '🚀',
    minPrestige: 0,
  },
  
  // --- PRESTIGE 1-2 ---
  {
    id: 'moon_base',
    name: 'Base Lunar',
    description: 'Gravedad baja, ganancias altas.',
    baseCost: 8500000,
    baseCps: 5000,
    owned: 0,
    iconStr: '🌑',
    minPrestige: 1,
  },
  {
    id: 'cloning_vat',
    name: 'Clonador de Minions',
    description: 'Tecnología prohibida para duplicar fuerza laboral.',
    baseCost: 45000000,
    baseCps: 12000,
    owned: 0,
    iconStr: '🧬',
    minPrestige: 1,
  },
  {
    id: 'dimension_portal',
    name: 'Portal Dimensional',
    description: 'Trae bananas de universos paralelos.',
    baseCost: 200000000,
    baseCps: 45000,
    owned: 0,
    iconStr: '🌀',
    minPrestige: 1,
  },
  {
    id: 'bananaverse',
    name: 'Bananaverso',
    description: 'Un universo hecho enteramente de potasio.',
    baseCost: 1500000000,
    baseCps: 150000,
    owned: 0,
    iconStr: '🌌',
    minPrestige: 2,
  },

  // --- PRESTIGE 3-5 ---
  {
    id: 'anti_gravity_lab',
    name: 'Lab. Antigravedad',
    description: 'Bananas que flotan directo a tu boca.',
    baseCost: 10000000000,
    baseCps: 550000,
    owned: 0,
    iconStr: '🧪',
    minPrestige: 3,
  },
  {
    id: 'spy_satellite',
    name: 'Satélite Espía',
    description: 'Encuentra bananas en los bolsillos de la gente.',
    baseCost: 35000000000,
    baseCps: 1200000,
    owned: 0,
    iconStr: '📡',
    minPrestige: 3,
  },
  {
    id: 'volcano_lair',
    name: 'Guarida Volcánica',
    description: 'La base clásica de todo supervillano.',
    baseCost: 80000000000,
    baseCps: 2500000,
    owned: 0,
    iconStr: '🌋',
    minPrestige: 4,
  },
  {
    id: 'mutagen_tank',
    name: 'Tanque de Mutágeno',
    description: 'Convierte cosas normales en cosas... raras.',
    baseCost: 400000000000,
    baseCps: 9500000,
    owned: 0,
    iconStr: '☢️',
    minPrestige: 5,
  },

  // --- PRESTIGE 6-9 ---
  {
    id: 'evil_bank',
    name: 'Banco del Mal',
    description: 'Inflación artificial de bananas.',
    baseCost: 3000000000000,
    baseCps: 45000000,
    owned: 0,
    iconStr: '🏦',
    minPrestige: 6,
  },
  {
    id: 'weather_machine',
    name: 'Máquina del Clima',
    description: 'Lluvia de bananas, literalmente.',
    baseCost: 25000000000000,
    baseCps: 180000000,
    owned: 0,
    iconStr: '⛈️',
    minPrestige: 7,
  },
  {
    id: 'time_machine',
    name: 'Máquina del Tiempo',
    description: 'Roba bananas antes de que se planten.',
    baseCost: 500000000000000,
    baseCps: 600000000,
    owned: 0,
    iconStr: '⏳',
    minPrestige: 8,
  },
  
  // --- PRESTIGE 10 (INFINITE) ---
  {
    id: 'infinite_banana',
    name: 'La Banana Infinita',
    description: 'Una singularidad amarilla. El fin y el principio.',
    baseCost: 5000000000000000,
    baseCps: 2500000000,
    owned: 0,
    iconStr: '♾️',
    minPrestige: 10,
  },

  // --- THE END GOAL ---
  {
    id: 'moon_heist',
    name: 'Robo de la Luna',
    description: 'El plan definitivo. Cómpralo para ganar el nivel.',
    baseCost: 25000000,
    baseCps: 0, 
    owned: 0,
    iconStr: '🌑',
    minPrestige: 0,
  },
];

export const INITIAL_UPGRADES: Upgrade[] = [
  // --- TIER 1 ---
  {
    id: 'plastic_gloves',
    name: 'Guantes de Plástico',
    description: 'Mejor agarre. x2 Click.',
    cost: 50,
    multiplier: 2,
    trigger: 15,
    owned: false,
    iconStr: '🧤',
  },
  {
    id: 'energy_drink',
    name: 'Refresco Púrpura',
    description: 'Energía inestable. x2 Click.',
    cost: 300,
    multiplier: 2,
    trigger: 100,
    owned: false,
    iconStr: '🥤',
  },
  {
    id: 'extra_arms',
    name: 'Brazos Extra',
    description: '¿Por qué tener solo dos? x2 Click.',
    cost: 1500,
    multiplier: 2,
    trigger: 500,
    owned: false,
    iconStr: '💪',
  },
  
  // --- TIER 2 ---
  {
    id: 'banana_fertilizer',
    name: 'Super Fertilizante',
    description: 'Las bananas crecen el doble de rápido. x2 Click.',
    cost: 5000,
    multiplier: 2,
    trigger: 2000,
    owned: false,
    iconStr: '💩',
  },
  {
    id: 'minion_union',
    name: 'Sindicato Minion',
    description: 'Mejores condiciones = mejor trabajo. x2.5 Click.',
    cost: 15000,
    multiplier: 2.5,
    trigger: 5000,
    owned: false,
    iconStr: '📜',
  },

  // --- TIER 3 ---
  {
    id: 'golden_banana',
    name: 'Banana Dorada',
    description: 'Brilla tanto que vale por tres. x3 Click.',
    cost: 50000,
    multiplier: 3,
    trigger: 20000,
    owned: false,
    iconStr: '✨',
  },
  {
    id: 'coffee_machine',
    name: 'Café para Todos',
    description: '¡Nadie duerme! x2 Click.',
    cost: 200000,
    multiplier: 2,
    trigger: 80000,
    owned: false,
    iconStr: '☕',
  },
  {
    id: 'king_bob',
    name: 'Corona de Rey Bob',
    description: '¡Manda a todos a trabajar! x5 Click.',
    cost: 1000000,
    multiplier: 5,
    trigger: 300000,
    owned: false,
    iconStr: '👑',
  },

  // --- PRESTIGE UPGRADES (Global Power) ---

  {
    id: 'freeze_ray_mod',
    name: 'Mod de Rayo Congelante',
    description: 'Congela el tiempo (metafóricamente). x5 Click.',
    cost: 10000000,
    multiplier: 5,
    trigger: 1000000,
    owned: false,
    iconStr: '❄️',
    minPrestige: 1,
  },
  {
    id: 'fart_gun',
    name: 'Pistola de Gases',
    description: 'Despeja la zona para trabajar mejor. x5 Click.',
    cost: 250000000,
    multiplier: 5,
    trigger: 50000000,
    owned: false,
    iconStr: '💨',
    minPrestige: 2,
  },
  {
    id: 'px41_serum',
    name: 'Suero PX-41',
    description: '¡TRANSFORMACIÓN! Poder violeta desatado. x10 Click.',
    cost: 500000000,
    multiplier: 10,
    trigger: 100000000,
    owned: false,
    iconStr: '💉',
    minPrestige: 5,
    effect: 'purple'
  },
  {
    id: 'gru_scarf',
    name: 'Bufanda de Gru',
    description: 'El estilo impone respeto. x8 Click.',
    cost: 5000000000000,
    multiplier: 8,
    trigger: 100000000000,
    owned: false,
    iconStr: '🧣',
    minPrestige: 6,
  },
  {
    id: 'plan_z',
    name: 'El Plan Z',
    description: 'Robar todo lo que no esté atornillado. x12 Click.',
    cost: 50000000000000,
    multiplier: 12,
    trigger: 1000000000000,
    owned: false,
    iconStr: '📜',
    minPrestige: 8,
  },
  // --- SKIN UPGRADES (Prestige 1-4, 6-10) ---
  // P1
  {
    id: 'suit_skin',
    name: 'Traje de Negocios',
    description: 'Un Minion profesional. x2 Click.',
    cost: 1000,
    multiplier: 2,
    trigger: 0,
    owned: false,
    iconStr: '👔',
    minPrestige: 1,
    effect: 'default' 
  },
  // P2
  {
    id: 'builder_skin',
    name: 'Casco de Obra',
    description: 'Seguridad ante todo. x2 Click.',
    cost: 10000,
    multiplier: 2,
    trigger: 0,
    owned: false,
    iconStr: '👷',
    minPrestige: 2,
    effect: 'default'
  },
  // P3
  {
    id: 'summer_skin',
    name: 'Minion Veraniego',
    description: '¡Bananaaaaa! x3 Click.',
    cost: 100000,
    multiplier: 3,
    trigger: 0,
    owned: false,
    iconStr: '🏖️',
    minPrestige: 3,
    effect: 'default'
  },
  // P4
  {
    id: 'hero_skin',
    name: 'Super Minion',
    description: 'Es un pájaro... es un avión... x4 Click.',
    cost: 1000000,
    multiplier: 4,
    trigger: 0,
    owned: false,
    iconStr: '🦸',
    minPrestige: 4,
    effect: 'default'
  },
  // P6
  {
    id: 'cyborg_skin',
    name: 'Ciborg Minion',
    description: 'Mitad banana, mitad máquina. x5 Click.',
    cost: 10000000,
    multiplier: 5,
    trigger: 0,
    owned: false,
    iconStr: '🤖',
    minPrestige: 6,
    effect: 'default'
  },
  // P7
  {
    id: 'wizard_skin',
    name: 'Mago Minion',
    description: '¡Abra Cadabra! x6 Click.',
    cost: 100000000,
    multiplier: 6,
    trigger: 0,
    owned: false,
    iconStr: '🧙',
    minPrestige: 7,
    effect: 'default'
  },
  // P8
  {
    id: 'ghost_skin',
    name: 'Minion Fantasma',
    description: 'Booo-nana. x7 Click.',
    cost: 1000000000,
    multiplier: 7,
    trigger: 0,
    owned: false,
    iconStr: '👻',
    minPrestige: 8,
    effect: 'default'
  },
  // P9
  {
    id: 'gold_skin',
    name: 'Minion de Oro',
    description: 'Vale su peso en oro. x8 Click.',
    cost: 10000000000,
    multiplier: 8,
    trigger: 0,
    owned: false,
    iconStr: '👑',
    minPrestige: 9,
    effect: 'default'
  },
  // P10
  {
    id: 'galaxy_skin',
    name: 'Minion Infinito',
    description: 'El poder del cosmos. x10 Click.',
    cost: 100000000000,
    multiplier: 10,
    trigger: 0,
    owned: false,
    iconStr: '🌌',
    minPrestige: 10,
    effect: 'galaxy'
  }
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  // --- WEALTH ---
  {
    id: 'beginner_collector',
    name: 'Recolector Novato',
    description: 'Consigue tus primeras 1,000 bananas.',
    iconStr: '🍌',
    conditionType: 'totalBananas',
    conditionValue: 1000,
  },
  {
    id: 'millionaire',
    name: 'Millonario',
    description: 'Alcanza 1,000,000 de bananas totales.',
    iconStr: '💰',
    conditionType: 'totalBananas',
    conditionValue: 1000000,
  },
  {
    id: 'billionaire',
    name: 'Billonario',
    description: 'Alcanza 1,000,000,000 de bananas totales.',
    iconStr: '🏦',
    conditionType: 'totalBananas',
    conditionValue: 1000000000,
  },
  
  // --- BUILDINGS ---
  {
    id: 'minion_horde',
    name: 'Ejército de Bebés',
    description: 'Ten 50 Minions Bebé.',
    iconStr: '👶',
    conditionType: 'building',
    conditionTarget: 'baby_minion',
    conditionValue: 50,
  },
  {
    id: 'farm_lord',
    name: 'Terrateniente',
    description: 'Construye 50 Granjas de Bananas.',
    iconStr: '🚜',
    conditionType: 'building',
    conditionTarget: 'banana_farm',
    conditionValue: 50,
  },
  {
    id: 'science_whiz',
    name: 'Científico Loco',
    description: 'Posee 25 Laboratorios de Gru.',
    iconStr: '⚗️',
    conditionType: 'building',
    conditionTarget: 'gru_lab',
    conditionValue: 25,
  },
  {
    id: 'space_race',
    name: 'Carrera Espacial',
    description: 'Despega con 10 Cohetes Espaciales.',
    iconStr: '🚀',
    conditionType: 'building',
    conditionTarget: 'rocket_ship',
    conditionValue: 10,
  },

  // --- PRESTIGE ---
  {
    id: 'first_step',
    name: 'Un Pequeño Paso',
    description: 'Realiza tu primer Renacimiento.',
    iconStr: '🌑',
    conditionType: 'prestige',
    conditionValue: 1,
  },
  {
    id: 'veteran_villain',
    name: 'Villano Veterano',
    description: 'Alcanza el Renacimiento 5.',
    iconStr: '🦹',
    conditionType: 'prestige',
    conditionValue: 5,
  },
  {
    id: 'infinite_power',
    name: 'Poder Infinito',
    description: 'Alcanza el Renacimiento 10 (Modo Infinito).',
    iconStr: '♾️',
    conditionType: 'prestige',
    conditionValue: 10,
  },
  
  // --- SPECIAL ---
  {
    id: 'moon_thief',
    name: 'Ladrón de Lunas',
    description: 'Roba la Luna (Completa una run).',
    iconStr: '🏆',
    conditionType: 'building',
    conditionTarget: 'moon_heist',
    conditionValue: 1,
  },
  {
    id: 'mutant_mayhem',
    name: 'Caos Mutante',
    description: 'Ten 10 Tanques de Mutágeno.',
    iconStr: '☢️',
    conditionType: 'building',
    conditionTarget: 'mutagen_tank',
    conditionValue: 10,
  }
];

export const SAVE_KEY = 'minion_mania_v2.4_achievements';
